### ISSUE TITLE
ModuleNotFoundError: No module named 'lib.training_schemes.'

### ISSUE THREAD

**Issue by ZGLCHN** [shamim-hussain/egt_triangular#2]
<img width="1053" alt="image" src="https://github.com/shamim-hussain/tgt/assets/97489779/ae665839-e2f2-40f0-b50c-8433c6e50b8e">

**Comment by shamim-hussain** [comment]
Can you please share the command you are running and the full traceback?

**Comment by ZGLCHN** [comment]
<img width="1728" alt="image" src="https://github.com/shamim-hussain/tgt/assets/97489779/0f490a66-0781-42f8-97ca-7f7de8f766b1">
As shown in the figure, I clicked on the red box to execute Python code and encountered these errors

ode/tgt-master/make_predictions.py"
Traceback (most recent call last):
  File "/Users/zhengguolin/Library/CloudStorage/OneDrive-个人/Project/Paper Code/tgt-master/m
  File "/Users/zhengguolin/Library/CloudStorage/OneDrive-个人/Project/Paper Code/tgt-master/make_predictions.py", line 6, in <module>
    execute('predict', config)
  File "/Users/zhengguolin/Library/CloudStorage/OneDrive-个人/Project/Paper Code/tgt-master/l
  File "/Users/zhengguolin/Library/CloudStorage/OneDrive-个人/Project/Paper Code/tgt-master/lib/training/execute.py", line 138, in execute
    scheme_class = import_scheme(config.get(KEY_SCHEME, SCHEME_DEFAULT))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/zhengguolin/Library/CloudStorage/OneDrive-个人/Project/Paper Code/tgt-master/l
  File "/Users/zhengguolin/Library/CloudStorage/OneDrive-个人/Project/Paper Code/tgt-master/lib/training/execute.py", line 57, in import_scheme
    imported_module = importlib.import_module(module_name)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Applications/anaconda3/envs/my-rdkit-env/lib/python3.12/importlib/__init__.py", line
  File "/Applications/anaconda3/envs/my-rdkit-env/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1324, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'lib.training_schemes.'

**Comment by ZGLCHN** [comment]
> Can you please share the command you are running and the full traceback?
<img width="1728" alt="image" src="https://github.com/shamim-hussain/tgt/assets/97489779/651862ea-facb-471d-a752-9b5a12c87588">
As shown in the figure, I clicked on the red box to execute Python code and encountered these errors
ode/tgt-master/make_predictions.py"
Traceback (most recent call last):
  File "/Users/zhengguolin/Library/CloudStorage/OneDrive-个人/Project/Paper Code/tgt-master/m
  File "/Users/zhengguolin/Library/CloudStorage/OneDrive-个人/Project/Paper Code/tgt-master/make_predictions.py", line 6, in <module>
    execute('predict', config)
  File "/Users/zhengguolin/Library/CloudStorage/OneDrive-个人/Project/Paper Code/tgt-master/l
  File "/Users/zhengguolin/Library/CloudStorage/OneDrive-个人/Project/Paper Code/tgt-master/lib/training/execute.py", line 138, in execute
    scheme_class = import_scheme(config.get(KEY_SCHEME, SCHEME_DEFAULT))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/zhengguolin/Library/CloudStorage/OneDrive-个人/Project/Paper Code/tgt-master/l
  File "/Users/zhengguolin/Library/CloudStorage/OneDrive-个人/Project/Paper Code/tgt-master/lib/training/execute.py", line 57, in import_scheme
    imported_module = importlib.import_module(module_name)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Applications/anaconda3/envs/my-rdkit-env/lib/python3.12/importlib/__init__.py", line
  File "/Applications/anaconda3/envs/my-rdkit-env/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1324, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'lib.training_schemes.'

**Comment by ZGLCHN** [comment]
> Can you please share the command you are running and the full traceback?

ode/tgt-master/make_predictions.py"
Traceback (most recent call last):
  File "/Users/zhengguolin/Library/CloudStorage/OneDrive-个人/Project/Paper Code/tgt-master/m
  File "/Users/zhengguolin/Library/CloudStorage/OneDrive-个人/Project/Paper Code/tgt-master/make_predictions.py", line 6, in <module>
    execute('predict', config)
  File "/Users/zhengguolin/Library/CloudStorage/OneDrive-个人/Project/Paper Code/tgt-master/l
  File "/Users/zhengguolin/Library/CloudStorage/OneDrive-个人/Project/Paper Code/tgt-master/lib/training/execute.py", line 138, in execute
    scheme_class = import_scheme(config.get(KEY_SCHEME, SCHEME_DEFAULT))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/zhengguolin/Library/CloudStorage/OneDrive-个人/Project/Paper Code/tgt-master/l
  File "/Users/zhengguolin/Library/CloudStorage/OneDrive-个人/Project/Paper Code/tgt-master/lib/training/execute.py", line 57, in import_scheme
    imported_module = importlib.import_module(module_name)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Applications/anaconda3/envs/my-rdkit-env/lib/python3.12/importlib/__init__.py", line
  File "/Applications/anaconda3/envs/my-rdkit-env/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1324, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'lib.training_schemes.'


<img width="1519" alt="image" src="https://github.com/shamim-hussain/tgt/assets/97489779/172e2fdd-e79b-43f2-8061-5e16df573565">

As shown in the figure, I clicked on the red box to execute Python code and encountered these errors.

**Comment by shamim-hussain** [comment]
You cannot simply run it as a script. You have to pass in command line arguments. For that, **you should use the console/terminal of your OS (powershell on windows, bash on linux etc.)**
1. Download the data and model weights as described in the README.
2. Make distance predictions (on the training and validation sets by default). Run the following command **from the terminal**
    ```
    python make_predictions.py configs/pcqm/tgt_at_200m/pcqm_dist_pred/tgt_at_100m_rdkit.yaml
    ```
    This will create a `predictions` directory (e.g. `bins50`) in the model directory, containing the predictions for the training and validation sets. To reduce the number of distance samples (and thus save time and disk space) add the following argument `'prediction_samples: 10'` (we used 50 samples, you can increase it during the final inference to get better results).
3. Final evaluation. Run the following command **from the terminal**
    ```
    python do_evaluations.py configs/pcqm/tgt_at_200m/pcqm_gap_pred/tgt_at_100m_rdkit.yaml
    ```
    the results will be printed to the console and also saved in the predictions directory

**Comment by ZGLCHN** [comment]
> You cannot simply run it as a script. You have to pass in command line arguments. For that, **you should use the console/terminal of your OS (powershell on windows, bash on linux etc.)**
> 
> 1. Download the data and model weights as described in the README.
> 2. Make distance predictions (on the training and validation sets by default). Run the following command **from the terminal**
>    ```
>    python make_predictions.py configs/pcqm/tgt_at_200m/pcqm_dist_pred/tgt_at_100m_rdkit.yaml
>    ```
>    
>    
>        
>          
>        
>    
>          
>        
>    
>        
>      
>    This will create a `predictions` directory (e.g. `bins50`) in the model directory, containing the predictions for the training and validation sets. To reduce the number of distance samples (and thus save time and disk space) add the following argument `'prediction_samples: 10'` (we used 50 samples, you can increase it during the final inference to get better results).
> 3. Final evaluation. Run the following command **from the terminal**
>    ```
>    python do_evaluations.py configs/pcqm/tgt_at_200m/pcqm_gap_pred/tgt_at_100m_rdkit.yaml
>    ```
>    
>    
>        
>          
>        
>    
>          
>        
>    
>        
>      
>    the results will be printed to the console and also saved in the predictions directory

Thank you for your previous reply.
According to README, I have correctly placed the data in the folder data/PCQM.
### But I don't know where the weight file should be placed?
Firstly, I obtained the weight file from Hugging Face.(models/pcqm/tgt_at_200m/dist_pred/tgt_at_dp_nordkit/checkpoint)
<img width="1279" alt="image" src="https://github.com/shamim-hussain/tgt/assets/97489779/01322da5-8521-4723-a297-c26185e86b71">

Secondly, in the tgt master project, I did not see `pcqm_dist_pred/tgt-at100m_rdkit.yaml`, so I have changed the code you provided to `dist_preprd/tgt-at-dp.nordkit.yaml`
<img width="501" alt="image" src="https://github.com/shamim-hussain/tgt/assets/97489779/4826cdd7-a2c3-45d0-8acb-57d34dbb4175">

As you can see, I placed model_state.pt files in the folder model and executed the command: 
`python make_predictions.py configs/pcqm/tgt_at_200m/dist_pred/tgt_at_dp_nordkit.yaml`
However, no new folder "predictions" was generated under the folder models
<img width="1416" alt="image" src="https://github.com/shamim-hussain/tgt/assets/97489779/15f07f83-7275-4161-b010-39fe5d65ce31">


If I place model_state.pt files under the tgt master folder, the result will be the same.
<img width="1396" alt="image" src="https://github.com/shamim-hussain/tgt/assets/97489779/2342b62b-e286-46c1-81c2-a84781107fe4">

**Comment by shamim-hussain** [comment]
You are right. There were errors in the instructions which have been corrected and the README has been updated. Please refer to this notebook <https://github.com/shamim-hussain/tgt/blob/master/inference_example.ipynb> where you  can find the full workflow for inference.

Alternatively, you may also follow these instructions -
1. Download the data.
2. Download the model weights. Maintain the same directory structure as provided in the huggingface repo, e.g., `models/pcqm/tgt_at_200m/dist_pred/tgt_at_dp_rdkit/checkpoint/model_state.pt`. (Alternatively, you can use the `huggingface-cli` tool to download the model weights as described in this notebook <https://github.com/shamim-hussain/tgt/blob/master/inference_example.ipynb> .)
3. Make distance predictions on the validation set
    ```
    python make_predictions.py configs/pcqm/tgt_at_200m/dist_pred/tgt_at_dp_rdkit.yaml 'predict_on: ["val"]'
    ```
    This will create a `predictions` directory (e.g. `bins50`) in the model directory, containing the predictions for the training and validation sets. To reduce the number of distance samples (and thus save time and disk space) add the following argument `'prediction_samples: 10'` (we used 50 samples, you can increase it during the final inference to get better results).
3. Final evaluation (on the validation set):
    ```
    python do_evaluations.py configs/pcqm/tgt_at_200m/gap_pred/tgt_at_tp_rdkit.yaml 'predict_on: ["val"]'
    ```
    the results will be printed to the console and also saved in the predictions directory.

**Comment by ZGLCHN** [comment]
> You are right. There were errors in the instructions which have been corrected and the README has been updated. Please refer to this notebook https://github.com/shamim-hussain/tgt/blob/master/inference_example.ipynb where you can find the full workflow for inference.
> 
> Alternatively, you may also follow these instructions -
> 
> 1. Download the data.
> 2. Download the model weights. Maintain the same directory structure as provided in the huggingface repo, e.g., `models/pcqm/tgt_at_200m/dist_pred/tgt_at_dp_rdkit/checkpoint/model_state.pt`. (Alternatively, you can use the `huggingface-cli` tool to download the model weights as described in this notebook https://github.com/shamim-hussain/tgt/blob/master/inference_example.ipynb .)
> 3. Make distance predictions on the validation set
>    ```
>    python make_predictions.py configs/pcqm/tgt_at_200m/dist_pred/tgt_at_dp_rdkit.yaml 'predict_on: ["val"]'
>    ```
>    
>    
>        
>          
>        
>    
>          
>        
>    
>        
>      
>    This will create a `predictions` directory (e.g. `bins50`) in the model directory, containing the predictions for the training and validation sets. To reduce the number of distance samples (and thus save time and disk space) add the following argument `'prediction_samples: 10'` (we used 50 samples, you can increase it during the final inference to get better results).
> 4. Final evaluation (on the validation set):
>    ```
>    python do_evaluations.py configs/pcqm/tgt_at_200m/gap_pred/tgt_at_tp_rdkit.yaml 'predict_on: ["val"]'
>    ```
>    
>    
>        
>          
>        
>    
>          
>        
>    
>        
>      
>    the results will be printed to the console and also saved in the predictions directory.

I have downloaded the Model weights to the local directory correctly according to your tutorial, and the data files have also been placed correctly.
However, when I followed the tutorial "Run Evaluation (Inference) Only on Validation Set", I did not receive the appropriate feedback. As shown in the following figure.

<img width="1424" alt="image" src="https://github.com/shamim-hussain/tgt/assets/97489779/a15d0c0d-98b9-47b9-a6a6-1e872a97da7c">

![image](https://github.com/shamim-hussain/tgt/assets/97489779/907899ac-178e-4ecd-a9ef-a5ae903278d4)

**Comment by shamim-hussain** [comment]
Can you please try running
```
python make_predictions.py configs/pcqm/tgt_at_200m/dist_pred/tgt_at_dp_rdkit.yaml 'predict_on: ["val"]' 'distributed: false' 'dataloader_workers: 0' 'prediction_samples: 4'
```

And then 

```
python do_evaluations.py configs/pcqm/tgt_at_200m/gap_pred/tgt_at_tp_rdkit.yaml 'predict_on: ["val"]' 'distributed: false' 'dataloader_workers: 0' 'prediction_samples: 4' 'bins_input_path: models/pcqm/tgt_at_200m/dist_pred/tgt_at_dp_rdkit/predictions/bins4'
```

What I've done here is

1. Turned off distributed training, which is only useful when you have multiple GPUs.
2. Turned off data loader workers. This spawns child processes by `fork`ing which sometimes causes problems on Windows.
3. Set number of samples to 4. This reduces inference cost (time and memory). Although you won't get the best possible result (we use 50 samples), this is good for preliminary test.

You can also take a look at this Google Colab Notebook where I have tested this. [https://colab.research.google.com/drive/1UJOXdt5VlP2QhiYpluGYnZukGFD0Wmoe?usp=sharing](https://colab.research.google.com/drive/1UJOXdt5VlP2QhiYpluGYnZukGFD0Wmoe?usp=sharing)

**Comment by ZGLCHN** [comment]
> Can you please try running
> 
> ```
> python make_predictions.py configs/pcqm/tgt_at_200m/dist_pred/tgt_at_dp_rdkit.yaml 'predict_on: ["val"]' 'distributed: false' 'dataloader_workers: 0' 'prediction_samples: 4'
> ```
> 
> And then
> 
> ```
> python do_evaluations.py configs/pcqm/tgt_at_200m/gap_pred/tgt_at_tp_rdkit.yaml 'predict_on: ["val"]' 'distributed: false' 'dataloader_workers: 0' 'prediction_samples: 4' 'bins_input_path: models/pcqm/tgt_at_200m/dist_pred/tgt_at_dp_rdkit/predictions/bins4'
> ```
> 
> What I've done here is
> 
> 1. Turned off distributed training, which is only useful when you have multiple GPUs.
> 2. Turned off data loader workers. This spawns child processes by `fork`ing which sometimes causes problems on Windows.
> 3. Set number of samples to 4. This reduces inference cost (time and memory). Although you won't get the best possible result (we use 50 samples), this is good for preliminary test.
> 
> You can also take a look at this Google Colab Notebook where I have tested this. https://colab.research.google.com/drive/1UJOXdt5VlP2QhiYpluGYnZukGFD0Wmoe?usp=sharing

Thank you very much for your patient reply.
I am now able to achieve the expected results by running the latest code you provided:
```
python make_predictions.py configs/pcqm/tgt_at_200m/dist_pred/tgt_at_dp_rdkit.yaml 'predict_on: ["val"]' 'distributed: false' 'dataloader_workers: 0' 'prediction_samples: 4'
```
I attempted to run this code on both Windows 11 and Mac systems, and both were successful.

Running on Mac：
<img width="1004" alt="image" src="https://github.com/shamim-hussain/tgt/assets/97489779/54c3553e-225f-4a52-9b5c-e64381a22a0c">

Running on Windows：
![e926720cee08e7e55403a2f2680685a6](https://github.com/shamim-hussain/tgt/assets/97489779/b2299460-1ff8-48b4-8405-4230272e8cec)
