### ISSUE TITLE
Code Error？

### ISSUE THREAD

**Issue by ZGLCHN** [shamim-hussain/egt_triangular#4]
In the "More About Training" section of your README.md, it mentions:

"# Stage 4 - Do final evaluation (and trim the model by removing the denoising head)
`python run configs/pcqm/tgt_at_200m/gap_pred/tgt_at_tp_rdkit.yaml"
`
Is this a correct Python command? Do you mean by that：
 `python run_training.py configs/pcqm/tgt_at_200m/gap_pred/tgt_at_tp_rdkit.yaml`?

**Comment by shamim-hussain** [comment]
You are right. This is a typo and you have the correct command. I have fixed it in the README. Thank you for pointing this out.
